version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=docker.for.mac.host.internal
      - EXECUTION_ID=444444
    volumes:
      - /Users/mendes/tech_interview/Kensho/applications/feature_selection/notebooks:/notebooks